### ISSUE TITLE
Fatal error detected - Failed to execute script presence

### ISSUE THREAD

**Issue by Pokemonjpups** [Discord-ian/ableton-presence#1]
this happens when I try to launch the exe.
**os**: windows 10 pro 64-bit
I am unable to use python.

**Comment by Discord-ian** [comment]
> Webserver was offline for maintenance at the time.
Added exception handler so that it doesn't error out.

**Comment by Discord-ian** [comment]
Fixed in https://github.com/Discord-ian/ableton-presence/commit/e503ccb54a8367f1cc6024a03a043b5fa30fb05d
