### ISSUE TITLE
Installation instructions unclear - how do you use this thing?

### ISSUE THREAD

**Issue by januszkrako** [Discord-ian/ableton-presence#2]
Hi. I can't find anything about this on the web - could you please clarify how to get this to work, from start to finish? Currently, the readme only tells you to put this in startup, which I have done. It seems so  redundant at the moment.

**Comment by Discord-ian** [comment]
In theory, it should open up on reboot and just run in the background. I have been working on an update that adds it to the system tray, with a menu. Let me know if you've tried restarting, and if that didn't work I can get you a version that'll print out everything it's doing, so we can solve the issue

**Comment by januszkrako** [comment]
It does run in the background according to Task Manager. On startup, I'm getting an error saying 'Fatal Error Detected - failed to execute script presence'. How to fix?
![image](https://user-images.githubusercontent.com/61183043/74991060-e2ea5380-543c-11ea-8167-17a29eab90ed.png)

**Comment by Discord-ian** [comment]
There's a few possibilities of what happened
>I missed an error while looking over 1.2.0
>Something is different for your system so the application runs into an error
>Some other random thing

I've attached a build of the application with full output. It'll open a command window with a decent amount of debug info. Let me know if it ends up working. If it doesn't, attach a screenshot/text output of the terminal window so I can work on fixing the issue

I've posted the debug version [here](http://im-stuck-in.space/dev/AbletonPresence_DEBUG.exe)

**Comment by januszkrako** [comment]
![image](https://user-images.githubusercontent.com/61183043/75900285-9b989580-5e34-11ea-8a9a-9ee600b539a4.png)
Hi, sorry for the overdue response. It detects the ableton client and my project title but I'm unsure on how to make it show up on discord now.

**Comment by Discord-ian** [comment]
Updated a few things within 55c34ab that should help. Go ahead and download 1.2.1 so you aren't stuck with the terminal constantly. Inside of Discord, make sure that you have "Display currently running game as a status message." turned on. That setting is inside of Game Activity. 

Closing this issue in 2 days if I don't hear anything back

**Comment by januszkrako** [comment]
Haha. I understand an open issue isn't a good look. I'm still unsure on how to make the status appear correctly on discord. I unchecked the 'Display currently running game as a status message' option, but I still don't see anything. AbletonPresence, Ableton Live and Discord are all running.
This is all I see in that menu.
![image](https://user-images.githubusercontent.com/61183043/75927860-1bd6ef00-5e65-11ea-882b-8c6425455a33.png)

**Comment by Discord-ian** [comment]
Are you set to Online (green) on Discord?

**Comment by januszkrako** [comment]
yes

**Comment by Discord-ian** [comment]
Interesting. It's showing that you're playing it in the game activity tab so it should be showing on your profile. Not exactly sure what else could be happening

**Comment by januszkrako** [comment]
It has just detected the normal Ableton Live application, but there is no additional status message that comes with it. Does the AbletonPresence app need to be selected as the running 'game' somehow by any chance?

**Comment by januszkrako** [comment]
As in, the status message shows that I'm running Ableton Live but none of the rich formatting stuff that AbletonPresence is supposed to do shows up.

**Comment by Discord-ian** [comment]
You might have the Ableton exe selected. I just looked for myself and it doesn't show any game there when the rich formatting stuff is active. I wonder if removing Ableton Live 10 (or whatever) from your "games" list would let the presence take over the status

**Comment by januszkrako** [comment]
I removed Live from my games list on discord. I also turned off Windows game mode and the 'do not disturb' list on my antivirus. The same thing happened. Any other suggestions?
![image](https://user-images.githubusercontent.com/61183043/75931448-e9c98b00-5e6c-11ea-9c15-fcf8d65102d7.png)

**Comment by januszkrako** [comment]
nvm it works. Just checked it with a buddy. Thanks for your trouble :)

**Comment by Discord-ian** [comment]
no worries! feel free to open up another one if something else arises
