### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by MarouaneMax** [Discord-ian/ableton-presence#3]
Hey ian
i'm having a problem running the scrip via the bat file and I keep getting this issue 
![brave_b8ZHmSWQCF](https://user-images.githubusercontent.com/38635147/87065615-2fc2a100-c209-11ea-8f74-d7aa50b3cffe.png)

Any solution ?

**Comment by Discord-ian** [comment]
What version of Python are you running? This project uses 3.5 and up.

**Comment by MarouaneMax** [comment]
i'm running py 3.7.6

**Comment by Discord-ian** [comment]
Have you tried running the command
```python -m pip install -U requests```
If that doesn't work, something might be wrong with your python install, although I'm not 100% I've tested this to work on 3.7 quite yet

**Comment by MarouaneMax** [comment]
Fixed by downloading the missing models manually  Thank you
