### ISSUE TITLE
Fatal error detected

### ISSUE THREAD

**Issue by aunight** [Discord-ian/ableton-presence#6]
![image](https://user-images.githubusercontent.com/52199445/174477641-31223c0d-1927-4b14-bdbb-88f19bb5bec0.png)

**Comment by simonSlamka** [comment]
+1

**Comment by Discord-ian** [comment]
Will look at tonight

**Comment by aunight** [comment]
still not work in any version :(

**Comment by Discord-ian** [comment]
So sorry!! Do you happen to know if you enabled Analytics when initially setting up the program?

**Comment by Discord-ian** [comment]
If you could attach your config file that would be very helpful! It should be accessible by hitting Windows + R and entering `%appdata%/AbletonPresence`

**Comment by aunight** [comment]
But I don't have any file and folder

**Comment by Discord-ian** [comment]
What OS are you running?

**Comment by aunight** [comment]
Windows 10

**Comment by Discord-ian** [comment]
Will update this issue when I have more information

**Comment by aunight** [comment]
ok

**Comment by Discord-ian** [comment]
I have located the issue, fix should be out within an hour hopefully

**Comment by Discord-ian** [comment]
This has been fixed in 93cf1bc , please go to the releases tab and download the latest version, 1.9.1. If you have any other issues please feel free to open a new issue.

**Comment by aunight** [comment]
But can I change the name to Ableton Live?
