### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by aunight** [Discord-ian/ableton-presence#7]
![image](https://user-images.githubusercontent.com/52199445/183481342-37658d8e-68e5-4048-bf03-4aaf70c1ba72.png)

**Comment by Discord-ian** [comment]
Did this occur immediately on launch or at a different time? Can you describe what you were doing when it happened

**Comment by aunight** [comment]
I just open the presence. 
Sometimes it will disappear in discord status when I re-open it will show this.
Even I use task manger to close all presence app.
It still happen.
Only way is to restart my pc

**Comment by Discord-ian** [comment]
Would you mind testing to see if this happens when you open Presence with Discord closed?

**Comment by aunight** [comment]
nope always discord open

**Comment by Discord-ian** [comment]
Closed as this has been inactive for more than a year
